"""Updated models

Revision ID: d18474a1b1f9
Revises: 4048518e18bc
Create Date: 2026-08-27 18:53:20.072292

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd18474a1b1f9'
down_revision: Union[str, Sequence[str], None] = '4048518e18bc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # SQLite has no ALTER COLUMN; batch mode rebuilds the table instead.
    with op.batch_alter_table('users') as batch_op:
        batch_op.alter_column('is_active',
                   existing_type=sa.BOOLEAN(),
                   nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users') as batch_op:
        batch_op.alter_column('is_active',
                   existing_type=sa.BOOLEAN(),
                   nullable=True)
    # ### end Alembic commands ###
